### ISSUE TITLE
device从group移除后的权限存在

### ISSUE THREAD

**Issue by huangxuankai** [nayotta/metathings#100]
### 疑是bug
* device加入到一个group的object后，拥有group中role的action，subject可以控制device
* 当device从group移除后，group中object查询不到device，但subject依旧可以操作device

#### 场景
* mtp平台上创建了application的entity，将application与device绑定到同一个group中，此group有一个role，role有以下操作权限：
```
patch_device
get_device

unary_call
stream_call

pull_frame_from_flow
push_frame_to_flow
query_frames_from_flow

put_object
remove_object
rename_object
get_object
get_object_content
get_object_streaming_content
list_objects

show_device
connect
heartbeat
```

* 通过application的凭证登录后，可以操作device
* 涉及的相关id
```
groupId: 193f9494586549379429bde31f1f7200
```

**Comment by PeerXu** [comment]
:rotating_light: 误报! 这是一次误报!
