### ISSUE TITLE
device连接5分钟后断开stream

### ISSUE THREAD

**Issue by zhanghuichina** [nayotta/metathings#39]
应该不是keepalive问题  pkg/common/client/helper.go  NewConnection 增加
kp := keepalive.ClientParameters{
		Time: 30 * time.Second,
	}

	opts = append(opts, grpc.WithKeepaliveParams(kp))
依然会断开

log:
deviced_1_3bb2cd9f56b1 | time="2019-04-03T10:02:14Z" level=debug msg="failed to recv dev res" #service=deviced dir="bridge(5cf323267dcc526b8eb4beb07434fc20)<-south(8f5edcabb53e44d8a3a242a56a449793)" epoch=0 error="rpc error: code = Canceled desc = context canceled"
deviced_1_3bb2cd9f56b1 | time="2019-04-03T10:02:14Z" level=debug msg="init producer" #bridge_driver=sarama #service=deviced bridge=5cf323267dcc526b8eb4beb07434fc20 topic=metathings.deviced.channel.5cf323267dcc526b8eb4beb07434fc20.from.south.to.north

**Comment by PeerXu** [comment]
问题出现在envoy代理上. 暂时没有找到原因.
通过grpc-client和grpc-server直连不会出现这种情况
